### ISSUE TITLE
Issues with PKGBUILDing kernel. (auto-optimization and patching brs.c)

### ISSUE THREAD

**Issue by sirjohndfox** [nine7nine/Linux-NSPA-pkgbuild#1]
Gday, 
I've just started trying to build your stuff on a fresh manjaro install.  I'm a longtime debian user, so I'm slowly feeling my way around pacman etc.    I managed to compile your wine repository no worries from the script.   I'm now working on the kernel.

Doing makepkg -i I've hit two snags.  

First:

`Setting config...

----------------------------------
| APPLYING AUTO-CPU-OPTIMIZATION |
----------------------------------
[*] DETECTED CPU (MARCH) : BDVER2

/home/john/Linux-NSPA-pkgbuild/linux-nspa/PKGBUILD: line 207: /home/john/Linux-NSPA-pkgbuild/linux-nspa/configure: No such file or directory
`
But i I run makepkg -i a second time I hit:

`patching file arch/x86/events/amd/brs.c
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file arch/x86/events/amd/brs.c.rej
patching file arch/x86/events/amd/core.c
==> ERROR: A failure occurred in prepare().
    Aborting...
`
If you have some time to help me sort this out, that would be great.

**Comment by sirjohndfox** [comment]
I need to learn more about kernel building on arch - probably no need for an issue here, sorry!

**Comment by nine7nine** [comment]
Hey there,

do you have the base-devel package installed?

also, you can't run makepkg again without first deleting the /src folder ~ makepkg will try to patch the kernel sources again, which is the error you are seeing above. Everytime you want to run makepkg, delete the /src and /pkg folders...

**Comment by nine7nine** [comment]
@sirjohndfox 

Not sure if you have tried to build this kernel again: but you shouldn't have any issue building it now. I changed some of the build options around and streamlined things. you still need to replace my config - but the issues you hit before shouldn't crop up.

just an fyi.

**Comment by sirjohndfox** [comment]
Thanks, I eventually fumbled my way through this script.  I did have trouble with use_optimization select
'if [ -n "$_use_optimization_select" ]; then
        source "${startdir}"/configure
        cpu_arch
    fi

'
There was no file called configure so I disabled it.
I'm interested in setting up the core of a one-man band too - may I ask what laptop and interface you use?   I'm on an old thinkpad with i7-6 with 16gb of ram with an old usb interface.   I probably need to upgrade I guess.  Money's a bit tight though.
Thanks again.
    On Monday, June 6, 2022 at 12:14:43 PM GMT+10, jrdnjhnstn ***@***.***> wrote:  
 
 


Hey there,

do you have the base-devel package installed?

also, you can run makepkg again without first deleting the /src folder ~ makepkg will try to patch the kernel sources again, which is the error you are seeing above. Everytime you want to run makepkg, delete the /src and /pkg folders...
