### ISSUE TITLE
current build fails...

### ISSUE THREAD

**Issue by revast** [nine7nine/Linux-NSPA-pkgbuild#3]
no luck so far with current build, fresh cloned, only change from default: 
_config_Surface7=

  CC      kernel/ucount.o
  CC      kernel/regset.o
  AR      arch/x86/events/built-in.a
  CC      mm/filemap.o
  CC      kernel/ksyms_common.o
  CC      arch/x86/xen/irq.o
  CC      kernel/groups.o
  CC      arch/x86/xen/multicalls.o
  CC      kernel/vhost_task.o
  AS      arch/x86/xen/xen-asm.o
  CC      arch/x86/xen/enlighten_pvh.o
  CC      kernel/sched/core.o
  CC      arch/x86/xen/trace.o
  CC      mm/mempool.o

In file included from kernel/sched/core.c:88:
kernel/sched/core.c: In function ‘update_rq_clock’:
kernel/sched/sched.h:2142:24: error: implicit declaration of function ‘static_branch_WARN_DOUBLE_CLOCK’; did you mean ‘SCHED_FEAT_WARN_DOUBLE_CLOCK’? [-Wimplicit-function-declaration]
 2142 | #define sched_feat(x) (static_branch_##x(&sched_feat_keys[__SCHED_FEAT_##x]))
      |                        ^~~~~~~~~~~~~~
kernel/sched/core.c:782:13: note: in expansion of macro ‘sched_feat’
  782 |         if (sched_feat(WARN_DOUBLE_CLOCK))
      |             ^~~~~~~~~~
kernel/sched/sched.h:2142:59: error: ‘__SCHED_FEAT_WARN_DOUBLE_CLOCK’ undeclared (first use in this function); did you mean ‘SCHED_FEAT_WARN_DOUBLE_CLOCK’?
 2142 | #define sched_feat(x) (static_branch_##x(&sched_feat_keys[__SCHED_FEAT_##x]))
      |                                                           ^~~~~~~~~~~~~
kernel/sched/core.c:782:13: note: in expansion of macro ‘sched_feat’
  782 |         if (sched_feat(WARN_DOUBLE_CLOCK))
      |             ^~~~~~~~~~
kernel/sched/sched.h:2142:59: note: each undeclared identifier is reported only once for each function it appears in
 2142 | #define sched_feat(x) (static_branch_##x(&sched_feat_keys[__SCHED_FEAT_##x]))
      |                                                           ^~~~~~~~~~~~~
kernel/sched/core.c:782:13: note: in expansion of macro ‘sched_feat’
  782 |         if (sched_feat(WARN_DOUBLE_CLOCK))
      |             ^~~~~~~~~~
kernel/sched/core.c: At top level:
kernel/sched/core.c:5531:12: warning: ‘cpu_resched_latency’ defined but not used [-Wunused-function]
 5531 | static u64 cpu_resched_latency(struct rq *rq)
      |            ^~~~~~~~~~~~~~~~~~~
make[4]: *** [scripts/Makefile.build:244: kernel/sched/core.o] Error 1
make[3]: *** [scripts/Makefile.build:485: kernel/sched] Error 2
make[2]: *** [scripts/Makefile.build:485: kernel] Error 2
make[2]: *** Waiting for unfinished jobs....

.
.
.

 UPD     arch/x86/kvm/kvm-asm-offsets.h
  AS [M]  arch/x86/kvm/vmx/vmenter.o
  AS [M]  arch/x86/kvm/svm/vmenter.o
  LD [M]  arch/x86/kvm/kvm-intel.o
  LD [M]  arch/x86/kvm/kvm-amd.o
make[1]: *** [/home/hero/Build/Linux-NSPA/Linux-NSPA-pkgbuild/linux-nspa/src/linux-6.10-rc6/Makefile:1937: .] Error 2
make: *** [Makefile:240: __sub-make] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by nine7nine** [comment]
bah...

it looks like when i updated the generic config i set a debug option that should be disabled... two options here:

1. unset _sched_feat_comp=y to _sched_feat_comp=
2. or wait until I fix the config (sometime later on today)

**Comment by nine7nine** [comment]
it should be fixed now.

I accidentally enabled CONFIG_SCHED_DEBUG which caused the compilation to fail. This is actually helpful though: because it's easy to fix in the source code, I had just forgot that I needed to address a few bits to allow enabling SCHED_DEBUG again, when using my 9999-sched_feat-compile-time.patch 

Next build I do locally, I am going to fix it up proper / allowing CONFIG_SCHED_DEBUG to be enabled again.

let me know how your build goes, then I will close this issue. Thanks!

**Comment by nine7nine** [comment]
Commit: https://github.com/nine7nine/Linux-NSPA-pkgbuild/commit/04991e60481e2c1fc3c15abc4987dfd95b6f1dc7 should fully resolve these issues, while also enabling CONFIG_SCHED_DEBUG ... Everything should work with _sched_feat_comp=y enabled, as well. I also properly used a macro around that one (unused) function there was a warning about too...

Let me know if any build issues persist!

**Comment by nine7nine** [comment]
Closing, as it should be fixed.
